---
title: "Figure5"
author: "Jianlou Yang"
date: "2021/4/21"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Fig.5a
```{r}
library(reshape2)

design = read.table("qPCR_mapping.txt", header=T, row.names= 1, sep="\t") 


tax_count_sum = as.data.frame(t(read.table("ITS_qPCR_fungal.txt",header = T,row.names = 1)))


mean_sort = tax_count_sum[(order(-rowSums(tax_count_sum))), ] # decrease sort
colSums(mean_sort)
mean_sort=as.data.frame(mean_sort)

mat_t <- as.data.frame(t(mean_sort))


design$group <- factor(design$group,levels=c("G1","G2"))
mat_t$group <- design$group
mat_t <- na.omit(mat_t)
data_all <- melt(mat_t, id="group", variable.name="genes", value.name = "value")
data_all1 <- data_all[-(which(data_all$value==0)),]

library(ggplot2)
library(ggpubr)

mycomparision <- list(c('G1', 'G2'))

p_1 <- ggplot(df_nooutlier, aes(x=group, y=log10(value),fill=group))+
  geom_boxplot()+
  stat_compare_means(method = 't.test', comparisons = mycomparision, label = 'p.signif') +
  theme_light()+ylab("log10(value)(Copies/μL)")+facet_wrap(~genes)
p_1

```
# Fig.4b
```{r}
dataplot <- read.csv("fungal_pcr.csv",header = T)
dataplot1 <- melt(dataplot,value.name = "number",variable.name = "group")
dataplot1 <- dataplot1[-20,]


dataplot1$time <- factor(dataplot1$time,levels = c("D58","D90","D123","D156","D216","D316","D330"))
dataplot1$group <- as.factor(dataplot1$group)

p2 <- ggplot(data = dataplot1, aes(x = time, y = number,color = group, shape = group,group=group)) + 
  geom_point(size = 3) + 
  geom_line(size=1) + 
  labs(x = "Time", y = "log(value+1)copies/m2")  
p2

```


# Fig.4c
```{r}
library(reshape2)

design = read.table("qPCR_mapping.txt", header=T, row.names= 1, sep="\t") 


tax_count_sum = as.data.frame(t(read.table("ITS_qPCR_fungal.txt",header = T,row.names = 1)))


mean_sort = tax_count_sum[(order(-rowSums(tax_count_sum))), ] # decrease sort
colSums(mean_sort)
mean_sort=as.data.frame(mean_sort)

mat_t1 <- as.data.frame(t(mean_sort))
design$time3 <- factor(design$time3,levels=c("D58","D90","D123","D156","D216","D316","D330"))
mat_t1$time3 <- design$time3
mat_t1 <- na.omit(mat_t1)
mat_mean = aggregate(mat_t1[,-6], by=mat_t1[6], FUN=mean) # mean
mat_mean_final = do.call(rbind, mat_mean)[-1,]

geno = mat_mean$time3
colnames(mat_mean_final) = geno
# Convert to data frame
mat_mean_final = as.data.frame(mat_mean_final)
# Add species column
mat_mean_final$genes = rownames(mat_mean_final)
library(ggpubr)

data_all = as.data.frame(melt(mat_mean_final, id.vars=c("genes")))
library(RColorBrewer)



mycomparision <- list(c("D58","D90","D123","D156","D216","D316","D330"))

compare_means(value ~variable, data=data_all, method = "kruskal.test")
colnames(data_all)[2] <- "Group"
p3 <- ggplot(data_all, aes(x=Group, y=log10(value+1),fill=Group))+  
  geom_boxplot()+ scale_fill_brewer(palette="Set1")+
  geom_point() +stat_compare_means()+
  #stat_compare_means(method = 'kruskal.test', comparisons = mycomparision, label = 'p.signif')+ 
  theme_light()+ylab("log10(value + 1)(Copies/μL)")#+facet_wrap(~genes)
p3
```

# Fig.5d Species and gene related network
```{r}
##The correlation coefficients between the abundance of microbial groups and the abundance of functional genes were calculated

library(Hmisc)
 
#Taking the genus level abundance as an example
phylum <- read.delim('genus_table.txt', row.name = 1, check.names = FALSE)
norm = t(t(phylum )/colSums(phylum ,na=T))*100
colSums(norm)


phylum <- as.data.frame(t(norm))



#Reading toxin gene table
genes <- read.delim('ITS_qPCR_fungal.txt', row.name = 1, check.names = FALSE)

#The correlation between community composition and function was calculated, and Spearman correlation coefficient was taken as an example
phylum_genes_corr <- rcorr(as.matrix(phylum), as.matrix(genes), type = 'spearman')
 
#Correlation coefficient r value and significance p value matrix
r <- phylum_genes_corr$r
p <- phylum_genes_corr$P
 

#Remove the correlation coefficient between microbe microbe and functional gene functional gene
r <- r[colnames(phylum),colnames(genes)]
p <- p[colnames(phylum),colnames(genes)]
r <- na.omit(r)
p <- na.omit(p)

write.csv(r,"r.csv")

r[abs(r) < 0.3] <- 0
 
#The correlation coefficient with P value less than 0.05 was selected, that is, P < 0.05
p <- p.adjust(p, method = 'BH')
p[p>=0.05] <- -1
p[p<0.05 & p>=0] <- 1
p[p==-1] <- 0
 
z <- r * p


z1 <- phylum_genes_corr$r
z1[z1 != 0 ] <- 0

z1[rownames(z),colnames(z)] <- z
z1[colnames(z),rownames(z)] <- z
z1[is.na(z1)] <- 0 
#write.table(data.frame(z1, check.names = FALSE), 'phylum_genes_corr.matrix.txt', col.names = NA, sep = '\t', quote = FALSE)
 
##network
library(igraph)
 
g <- graph.adjacency(z1, weighted = TRUE, mode = 'undirected')
g

g <- delete.vertices(g, names(degree(g)[degree(g) == 0]))
 
E(g)$correlation <- E(g)$weight
E(g)$weight <- abs(E(g)$weight)
 
plot(g)


#For example, GML format can be opened and edited visually by using Cytoscape or gephi software
write.graph(g, 'network.gml', format = 'gml')
write.graph(g, 'network.graphml', format = 'graphml')
```




